### ISSUE TITLE
[feature request] Embedding Custom CAs

### ISSUE THREAD

**Issue by MAHDTech** [siderolabs/image-factory#121]
Would it be possible to have a box during image creation where you can paste a CA Chain and have it embedded into the generated image.

Then have the same feature available from Omni which passes it as an argument.

**Comment by smira** [comment]
This is not available in Talos Linux, so Image Factory can't help here much, it never modifies original Talos Linux image.

**Comment by smira** [comment]
(but the feature itself makes sense)

**Comment by MAHDTech** [comment]
Makes sense, thanks!

**Comment by andrewrynhard** [comment]
We just planned a solution. https://github.com/siderolabs/talos/issues/8867
