### ISSUE TITLE
Image Factory broken for v1.7.5

### ISSUE THREAD

**Issue by tjwallace** [siderolabs/image-factory#124]
I cannot get past this step: https://factory.talos.dev/?platform=metal&target=metal&version=1.7.5

EDIT: I can get to the end of the wizard, but cannot download an ISO. Server returns 500.
Example: https://factory.talos.dev/image/922571c4ce7bd42c58e3b2e06a119fb3b1172711bd2f23a769d893a732d75773/v1.7.5/metal-amd64.iso

**Comment by keatontaylor** [comment]
Similar issue, does appear that the factory image pages load, but attempting to pull an image it provides, or download an ISO, etc results in a 500 internal server error.

**Comment by keatontaylor** [comment]
Still having an issue where a schematic ID has versions for 1.7.4 (and all the way back to 1.6.4) but does not have an image and returns a 500 internal server error when attempting to pull 1.7.5.

Schematic ID: 859dd30ac3e1f9f0aa5e425e347525e0090e0d2329517ee2f52754c82e680c7f 

<img width="1166" alt="image" src="https://github.com/siderolabs/image-factory/assets/657559/b7e434fd-1ee7-4877-be02-c58d14b92665">

**Comment by frezbo** [comment]
This should be fixed now.

**Comment by keatontaylor** [comment]
As much as I wish it was:

<img width="1080" alt="image" src="https://github.com/siderolabs/image-factory/assets/657559/36252af8-7d18-4370-bd81-d0727dafe8c0">

Same error as of this comment.

**Comment by ishioni** [comment]
Same here
```
docker pull factory.talos.dev/installer/11ed13003eb3e3bda0bbbcc531fa4a457a3e80ae62378d2cb2bb92f35b5b3149:v1.7.5                                         
Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
```

**Comment by frezbo** [comment]
Apologies, one of the image signing steps failed and hadn't noticed that, should be good to go now.
