### ISSUE TITLE
Generates images that do not boot

### ISSUE THREAD

**Issue by smst329** [siderolabs/image-factory#157]
Downloaded an image factory iso. Did a dd to usb stick. It is not detected as bootable. Standard ISO downloading from github releases for talos linux is bootable after dd to usb stick, so there is something off between your release ISO and the image factory iso.

ISO was amd64 metal with secureboot.

Even the secure boot image factory link from the secure boot documentation page does not produce a usb that is detectable as bootable.

When I flip back and dd the github releases ISO, it is immediately able to boot again. This behavior is observed with secure boot enabled, secure boot in setup mode, and secure boot disabled.

**Comment by frezbo** [comment]
This is fixed by https://github.com/siderolabs/talos/issues/9565, will be updated in image factory later this week

**Comment by frezbo** [comment]
Will be fixed via #156

**Comment by smst329** [comment]
NIce! I'll give it a try! Hopefully I won't run back into the bug where a bootable ISO breaks as it starts up! But that's another issue on another repo. Feel free to close if you'd like, I can reopen if I see issues or file another. Thank you very much!
