### ISSUE TITLE
VMWare build "non-functional" on ARM64 builds of image-factory

### ISSUE THREAD

**Issue by mattiascockburn** [siderolabs/image-factory#164]
Cheers!

We are running image-factory on ARM64 and were just debugging an interesting issue where default kernel parameters were not propagated to vmware ova/iso builds. It all leads to [this commit](https://github.com/siderolabs/talos/commit/3b42f56f43217cd6f3188378ac8baa6f82e2cbc3). Are there any plans to make this working again on ARM64?

**Comment by smira** [comment]
Yes, nice catch, some methods should be defined for all architectures.

**Comment by mattiascockburn** [comment]
Thanks @smira for your blazingly fast reply and fix <3
