### ISSUE TITLE
Bug: invalid scematic customazation is accepted

### ISSUE THREAD

**Issue by samip5** [siderolabs/image-factory#177]
Factory shouldn't accept input that it deems invalid due to eg the fact it uses an overlay image which is not official.

```
2024/12/16 20:32:29 DEBUG defined schematic:
overlay:
    image: registry.skysolutions.fi/library/sbc-raspberrypi:alpha.1-1@sha256:f5734630fbae0647daf6e490ff91cd5f95220c3fc34e64364b2f245cde502a43
    name: sbc-raspberrypi
customization: {}
2024/12/16 20:32:29 DEBUG generating schematic ID from https://factory.talos.dev/schematics
2024/12/16 20:32:29 DEBUG installer URL for w7 is set to: factory.talos.dev/installer/ec42c5ed12094ebe3fb1c628bffbc3d242b614319205c2958665cdcdfd723b06:v1.9.0-beta.1
```

That schematic cannot be used as the asset generation throws a fit.

**Comment by smira** [comment]
I'm not sure what the issue is. The final validity of the schematic can be only determined for a specific version of Talos (when the schematic is being used). 

The set of overlays is dynamic per Talos version.

**Comment by samip5** [comment]
When it throws a fit, is when you actually try to eg upgrade the node using that generated schematic ID.

This is when it throws a fit for a example:
```
talosctl upgrade --preserve -n 10.0.105.32 --debug -i factory.talos.dev/installer/ec42c5ed12094ebe3fb1c628bffbc3d242b614319205c2958665cdcdfd723b06:v1.9.0-beta.1 -m powercycle

dmesg:
10.0.105.32: user: warning: [2024-12-16T19:14:57.772971776Z]: [talos] upgrade request received: staged false, force false, reboot mode POWERCYCLE
10.0.105.32: user: warning: [2024-12-16T19:14:57.783360776Z]: [talos] validating "factory.talos.dev/installer/ec42c5ed12094ebe3fb1c628bffbc3d242b614319205c2958665cdcdfd723b06:v1.9.0-beta.1"
10.0.105.32: user: warning: [2024-12-16T19:14:58.474082776Z]: [talos] retrying error: failed to pull image "factory.talos.dev/installer/ec42c5ed12094ebe3fb1c628bffbc3d242b614319205c2958665cdcdfd723b06:v1.9.0-beta.1": failed to resolve reference "factory.talos.dev/installer/ec42c5ed12094ebe3fb1c628bffbc3d242b614319205c2958665cdcdfd723b06:v1.9.0-beta.1": unexpected status from HEAD request to https://factory.talos.dev/v2/installer/ec42c5ed12094ebe3fb1c628bffbc3d242b614319205c2958665cdcdfd723b06/manifests/v1.9.0-beta.1: 400 Bad Request
```

**Comment by smira** [comment]
yes, it does, but there's no way to validate it before you try to access it. 

use the wizard if unsure, follow the official documentation for the API to get available values for the field, and you'll be good to go.

**Comment by samip5** [comment]
> use the wizard if unsure, follow the official documentation for the API to get available values for the field, and you'll be good to go.

What's the reason why the official factory couldn't be used with custom overlays? The limit on it that is artificial.

**Comment by smira** [comment]
> > use the wizard if unsure, follow the official documentation for the API to get available values for the field, and you'll be good to go.
> 
> What's the reason why the official factory couldn't be used with custom/non-official overlays? The limit on that is artificial.

You can run your own where you can set your own rules, but our official instance will only serve official images.
