### ISSUE TITLE
Support for alpha version?

### ISSUE THREAD

**Issue by budimanjojo** [siderolabs/image-factory#45]
Hello, is there any plan to support alpha version? i.e right now will be `v1.6.0-alpha.1`. If I put it in the url it will just return with Internal Server Error.

Thank you.

**Comment by smira** [comment]
if the alpha version doesn't work, it'd be a bug.

**Comment by budimanjojo** [comment]
@smira I was trying v1.5.0-alpha.3 and v1.6.0-alpha.1 yesterday.
Now, I just tried again and v1.6.0-alpha.1 works but not v1.5.0-alpha.3.

Visiting here will return status 500: https://factory.talos.dev/image/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/v1.5.0-alpha.3/metal-amd64.iso

**Comment by budimanjojo** [comment]
But v1.5.0-beta.0 works.

At least the latest alpha works now (not sure why it didn't yesterday but maybe my mistake). so feel free to close this issue.

**Comment by smira** [comment]
Old alphas don't have proper image signatures on container images, I hope nobody is using them for real :)
