### ISSUE TITLE
[enhancement] show SBC image references on factory webpage

### ISSUE THREAD

**Issue by Ornias1993** [siderolabs/image-factory#64]
The factory website does not show any SBC image links (including raspberry pi).
Manually alterting the url does lead to a downloadable image.

**Comment by smira** [comment]
![image](https://github.com/siderolabs/image-factory/assets/55211/a7a67291-d72f-4c73-85a1-3bc4e19d8062)

**Comment by Ornias1993** [comment]
I'm a blind man!
Still would be nice to have them easily available...

**Comment by frezbo** [comment]
Should be fixed by https://github.com/siderolabs/image-factory/pull/94

**Comment by smira** [comment]
Image Factory provides URLs now for a specific SBC
