### ISSUE TITLE
Raspberry Pi image through factory not working

### ISSUE THREAD

**Issue by Ornias1993** [siderolabs/image-factory#65]
Test env:
3x raspberry Pi 4, 3 different high grade sd sd cards, official power supply.

Official image:
Loads fine.

After manually generating a raspberry pi url through the image factory with just 2 kernel args:
https://factory.talos.dev/image/8e3aaa276e2b5ccbe7243708ef6a9c9ca80901b986232474eb8259627fec45db/v1.5.5/rpi-arm64.raw.xz

Kernel args where to disable mac-based ethernet interface names and disable ipv6.
Nothing major.

I loaded this to the SD cards the same way as the offical image and it fails booting with 4 blinks.

**Comment by Ornias1993** [comment]
Additional research:
Stock image == working.

Image with ONLY this through factory not working:
```
customization:
    extraKernelArgs:
        - net.ifnames=0
```

**Comment by smira** [comment]
Thanks, we will look into that

**Comment by smira** [comment]
The fix was deployed.
