### ISSUE TITLE
image-factory and arm64

### ISSUE THREAD

**Issue by jahanson** [siderolabs/image-factory#74]
Unable to prepare arm64 images on same system as preparing amd64

I was able to get everything setup on a bare-metal setup for image-factory but i'm not sure how you're preparing the hcloud arm64 xz on the same system (assuming image-factory is on an amd64). grub install is balking at a arm64 dependency that I can't seem to find in any debian registry for amd64. Just looking for some advice on how you set it up to do both archs on the same system.

**Comment by smira** [comment]
Sorry, not sure what do you mean by that? Image Factory has a container image which has all dependencies included.

Running with custom dependencies on the host is possible, but not recommended, as you'd need to have everything set up exactly same way.

**Comment by jahanson** [comment]
I guess I've been doing this the hard way and I didn't even realize. I'll check the container setup. Thank you!
