### ISSUE TITLE
amdgpu-firmware is not available in talos 1.5.x

### ISSUE THREAD

**Issue by linuxmaniac** [siderolabs/image-factory#89]
extensions are available for 1.6.x
![image](https://github.com/siderolabs/image-factory/assets/63080/f7747111-aa48-464f-8b17-cafce96f6657)
but not for 1.5.6
![image](https://github.com/siderolabs/image-factory/assets/63080/d660d73e-c0ee-4e79-8de5-5d430b0cfd6e)

**Comment by frezbo** [comment]
amdgpu firmware was only added for talos 1.6+, we could probably enable if we do another 1.5 release which won;t happen unless there's some critical CVE.

Also the fix for ROCM is only available for 1.6+
