### ISSUE TITLE
Schematic ID is not consistent due to ordering

### ISSUE THREAD

**Issue by onedr0p** [siderolabs/image-factory#99]
Schematic ID is not consistent due to rendered ordering of system extensions, it would be nice if this was consistent for reproducibility.

To reproduce:

1. Go to https://factory.talos.dev/
2. Select some system extensions
3. Submit and see it generate a schematic ID
<img width="899" alt="image" src="https://github.com/siderolabs/image-factory/assets/213795/4c5cf860-51f4-43c2-a048-842e00ce15b2">
4. Click submit again, and again and again and notice how the ordering of the system extensions changes and so does the schematic ID
<img width="846" alt="image" src="https://github.com/siderolabs/image-factory/assets/213795/a96a37ce-2194-46dd-904d-cb86799ba00e">

I am curious if setting an ordering on the system extensions before the processing takes place will address this issue?

**Comment by smira** [comment]
Order of extensions technically changes the output, as the order of extensions might matter (they are overlaid on top of another). Our extensions don't have side-effects, but still order changes the output.

You can skip using UI and use API directly for exact reproducibility.

**Comment by smira** [comment]
But certainly we can do better job in the UI.

**Comment by onedr0p** [comment]
Thanks @smira, it's not a huge issue but might confuse some people who are not aware of this nuance.
